environment:
  matrix:
  - julia_version: 0.6
  - julia_version: 0.7
  - julia_version: 1.0

platform:
  - x86 # 32-bit
  - x64 # 64-bit

# Precompilation of GLPK.jl crashes for an unknown reason on x86 on 0.7 and
# 1.0. See https://github.com/JuliaLang/julia/issues/28736.
matrix:
  allow_failures:
  - julia_version: 0.7
    platform: x86
  - julia_version: 1.0
    platform: x86

branches:
  only:
    - master
    - /release-.*/

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

install:
  - ps: iex ((new-object net.webclient).DownloadString("https://raw.githubusercontent.com/JuliaCI/Appveyor.jl/version-1/bin/install.ps1"))

build_script:
  - echo "%JL_BUILD_SCRIPT%"
  - C:\julia\bin\julia -e "%JL_BUILD_SCRIPT%"

test_script:
  # - C:\julia\bin\julia -e "VERSION >= v\"0.7-\" && (using Pkg; Pkg.add(\"LinQuadOptInterface\"); using LinQuadOptInterface)"
  - echo "%JL_TEST_SCRIPT%"
  - C:\julia\bin\julia -e "%JL_TEST_SCRIPT%"
